openapi: 3.0.0
info:
  title: Golden Fleece API
  version: 1.0.0
  description: A simple REST API for providing basic CRUD-access to the employees
    in a Golden Fleece database.
servers:
  - url: http://localhost:3600
    description: gf-server-api
schemes:
  - http
  - https
apis:
  - ./src/routes/*.ts
paths:
  /api/ask-admin:
    post:
      tags:
        - Mail
      summary: Comment or question to admin
      description: Comment or question to admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: customers name
                email:
                  type: string
                  description: customers email
                phone:
                  type: string
                  description: customers phone
                message:
                  type: string
                  description: customers comment or question addressed to admin
              required:
                - email
                - name
                - message
              example:
                email: example@gmail.com
                name: Ivan
                phone: 379221233209
                message: Could you help me to bring my baggage
      responses:
        "200":
          description: Mail sent.
  /api/booking-request:
    post:
      tags:
        - Mail
      summary: Customer trying to book room
      description: Customer trying to book room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: customers email
                name:
                  type: string
                  description: customers name
                dateIn:
                  type: string
                  description: check in date yyyy-mm-dd
                dateOut:
                  type: string
                  description: check out date yyyy-mm-dd
                roomNumber:
                  type: number
                  description: room number
                adultsAmount:
                  type: number
                  description: adults amount
                childrenAmount:
                  type: number
                  description: children amount
                phone:
                  type: string
                  description: customers phone
                message:
                  type: string
                  description: customers comment or question addressed to admin
              required:
                - email
                - name
                - dateIn
                - dateOut
                - roomNumber
                - adultsAmount
                - childrenAmount
              example:
                email: example@gmail.com
                name: Ivan
                dateIn: 2017-01-26
                dateOut: 2017-02-12
                roomNumber: 12
                adultsAmount: 2
                childrenAmount: 1
                phone: 379221233209
                message: Could you help me to bring my baggage?
      responses:
        "200":
          description: Message sent
  /api/rooms:
    get:
      tags:
        - Rooms
      summary: Get list of rooms
      description: Retrieve a list of all rooms
      responses:
        "200":
          description: A list of rooms.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    dateIn:
                      type: string
                      description: check in date yyyy-mm-dd
                    dateOut:
                      type: string
                      description: check out date yyyy-mm-dd
                  required:
                    - dateIn
                    - dateOut
                  example:
                    dateIn: 2017-01-26
                    dateOut: 2017-02-12
    post:
      tags:
        - Test
      summary: Comment or question to admin
      description: Comment or question to admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                apartmentsType:
                  type: string
                  description: the room's type
                services:
                  type: string
                  description: the room's services
                id:
                  type: string
                  description: the room's ID
                description:
                  type: string
                  description: short room's description
                descriptionLong:
                  type: string
                  description: the room's description
                price:
                  type: number
                  description: the room's price
                square:
                  type: number
                  description: the room's square
                adults:
                  type: number
                  description: amount of adults who can stay in the room
                promo:
                  type: string
                  description: the room's promo image URL
                rating:
                  type: number
                  description: the room's rating
              required:
                - apartmentsType
                - services
                - id
                - description
                - descriptionLong
                - price
                - square
                - adults
                - promo
                - rating
              example:
                apartmentsType: Single
                services: WiFi, TeaCoffeeMaker
                id: 1
                description: A small room
                descriptionLong: Dressed in soothing natural colour palettes with designs
                  inspired by the natural landscape...
                price: 300
                square: 25
                adults: 2
                promo: https://uploads-ssl.webflow.com/5e38379f9141a20d42ea7ab3/618177a1165e33f6ca935321_506.jpg
                rating: 10
      responses:
        "200":
          description: Mail sent.
  "/api/rooms/{room_id}":
    get:
      tags:
        - Room
      summary: Get room by ID
      description: Retrieve a room by ID
      responses:
        "200":
          description: Room.
          content:
            application/json:
              schema:
                $ref: "#components/schema/Room"
    put:
      tags:
        - Room
      summary: Update room information by ID
      description: Update room by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/schema/Room"
      responses:
        "200":
          description: Room.
          content:
            application/json:
              schema:
                $ref: "#components/schema/Room"
    delete:
      tags:
        - Room
      summary: Delete room by ID
      description: Delete a room by ID
      responses:
        "200":
          description: Successful room delete.
          content:
            application/json: {}
components:
  schema:
    Room:
      type: object
      properties:
        dateIn:
          type: string
          description: check in date yyyy-mm-dd
        dateOut:
          type: string
          description: check out date yyyy-mm-dd
      required:
        - dateIn
        - dateOut
      example:
        dateIn: 2017-01-26
        dateOut: 2017-02-12
tags: []
